version: "3.8"

networks:
  numbfish_network:
    driver: bridge

services:
  numbfish-redis:
    container_name: numbfish-redis
    image: redis
    networks:
      - numbfish_network
    environment:
      - REDIS_PASSWORD=iotG@2025
    ports:
      - 8379:6379
    restart: unless-stopped

  numbfish-mysql:
    container_name: numbfish-mysql
    image: mysql
    networks:
      - numbfish_network
    environment:
      - MYSQL_ROOT_PASSWORD=iotG@2025
      - MYSQL_DATABASE=iotgenius
      - MYSQL_PASSWORD=iotG@2025
    ports:
      - 8306:3306
    restart: unless-stopped

  numbfish-auth:
    container_name: numbfish-auth
    image: numbfish-auth
    depends_on:
      - numbfish-redis
      - numbfish-mysql
    networks:
      - numbfish_network
    ports:
      - 9999:9999
    restart: unless-stopped