version: "3.8"

networks:
  numbfish_network:
    driver: bridge

services:
  numbfish-redis:
    container_name: numbfish-redis
    image: redis
    networks:
      - numbfish_network
    environment:
      - REDIS_PASSWORD=iotG@2025
    ports:
      - 6379:6379
    restart: unless-stopped

  numbfish-mysql:
    container_name: numbfish-mysql
    image: mysql
    networks:
      - numbfish_network
    environment:
      - MYSQL_ROOT_PASSWORD=iotG@2025
      - MYSQL_DATABASE=iotgenius
      - MYSQL_PASSWORD=iotG@2025
    ports:
      - 3306:3306
    restart: unless-stopped

  numbfish-authorization:
    container_name: numbfish-authorization
    image: numbfish-authorization
    depends_on:
      - numbfish-redis
      - numbfish-mysql
    networks:
      - numbfish_network
    environment:
      - SERVER_PORT=9998
      - KNIFE4J_ENABLED=true
      - KNIFE4J_USERNAME=numbfish
      - KNIFE4J_PASSWORD=numbfish
      - MYSQL_HOST=numbfish-mysql
      - MYSQL_PORT=3306
      - MYSQL_SCHEMA=iotgenius
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=iotG@2025
      - REDIS_HOST=numbfish-redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=iotG@2025
      - REDIS_DATABASE=0
    ports:
      - 9998:9998
    restart: unless-stopped