server:
  port: 9999
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/iotgenius?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: iotgenius
    password: iotG2025!@#
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      auto-commit: true
      minimum-idle: 2
      idle-timeout: 60000
      connection-timeout: 30000
      max-lifetime: 1800000
      pool-name: DatebookHikariCP
      maximum-pool-size: 5
      connection-test-query: SELECT 1
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: iotG2025!@#
      database: 0
      jedis:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0
  sql:
    init:
      data-locations: classpath:database/data.sql
      mode: never
      continue-on-error: false
      encoding: UTF-8
      separator: ;
app:
  store:
    path: /root/service/spirit/data
  mqtt:
    enabled: true
    url: tcp://127.0.0.1:1883
    username: spirit_prod_new_u_${random.value}
    password: ${random.value}
    clientId: spirit_prod_new_c_${random.value}
    topics:
      mixin:
        enabled: true
        name: /dev/mixin
      state:
        enabled: true
        name: /dev/state
      parameter:
        enabled: true
        name: /dev/msg
      connect:
        enabled: true
        name: /dev/conn
  influx2:
    enabled: true
    url: http://127.0.0.1:8086
    org: iotgenius
    token: 1cTYtXvHh60yBnvut3yJDaaGg4q9GXWBeC8HzSAtrNXl_KR1uKcbzNC4TCkV0QW1i_abASrZpsMASjv31oZoig==
    bucket: iotgenius
    measurements:
      device-parameter: DeviceParameter
      device-connect: DeviceConnect
      device-state: DeviceState
      device-produce: DeviceProduce
  alias:
    device-code: deviceCode
    timestamp: timestamp
    state: Status
    produce: produce
    event: event
  cache:
    high: 60
    media: 180
    low: 600
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
